### ISSUE TITLE
Menu bar word-wraps on narrow displays, covering map

### ISSUE THREAD

**Issue by xenimax** [bravecollective/intel-tool#2]
The menu bar at the head of the Brave Intel Map has become so filled with menus and links that it no longer fits on any browser window with a canvas less than 1095px wide.  When viewed on a browser with an effective width narrower than that (a browser snapped to half-screen on a 1080p monitor, at least some Android tablets, any any iPad) the menu bar wraps to a second (or third) line, causing it to overlap the map and render the northern part of the region unviewable.

To reproduce:  Resize the browser so that the canvas has a width less than 1095px and more than 767px

Screenshots demonstrating problem:
![brave intel bug](https://cloud.githubusercontent.com/assets/8931932/4426048/89d9a954-45af-11e4-9cf2-82bc8ab962af.jpg)

**Comment by Serinus1** [comment]
Still an issue at 900x800 or so.

http://serinus.us/screenshots/20150127004121172.png
